name: Tests
on:
  workflow_call:
jobs:
  lints:
    name: lint_fmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go 1.25.1
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.1
        id: go
      - run: go version
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - run: go vet ./...
      - run: |
          gofmt -s -l .
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      - run: golangci-lint run
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go 1.25.1
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.1
        id: go
      - run: go install golang.org/x/tools/gopls@latest
      - run: go test ./...
